---
name: Check SUSE QA Tools WIP-Limit and set due dates
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 4 * * *'
env:
  redmine_api_key: ${{ secrets.REDMINE_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install curl jq
      - name: Check SUSE QE Tools WIP-Limit
        run: sh -ex backlog-check-wip-limit
      - name: Set SUSE QE Tools due dates
        run: sh -ex backlog-set-due-date
